- global/src/main/kotlin/com/fx/global/api/Api.kt
- global/src/main/kotlin/com/fx/global/exception/handler/MethodArgumentNotValidExceptionHandler.kt
- user/src/main/kotlin/com/fx/user/UserApplication.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/UserOpenApiAdapter.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/dto/UserSignUpRequest.kt
> feat: 공통 유효성검증 예외 Handler 개발

- post/src/main/java/com/fx/post/adapter/out/persistence/entity/BaseEntity.java
- post/src/main/java/com/fx/post/adapter/out/persistence/entity/CommentEntity.java
- post/src/main/java/com/fx/post/adapter/out/persistence/entity/LikeEntity.java
- post/src/main/java/com/fx/post/adapter/out/persistence/entity/PostEntity.java
- post/src/main/java/com/fx/post/adapter/out/persistence/entity/PostMediaEntity.java
- post/src/main/java/com/fx/post/adapter/out/persistence/repository/CommentRepository.java
- post/src/main/java/com/fx/post/adapter/out/persistence/repository/LikeRepository.java
- post/src/main/java/com/fx/post/adapter/out/persistence/repository/PostMediaRepository.java
- post/src/main/java/com/fx/post/adapter/out/persistence/repository/PostRepository.java
- post/src/main/kotlin/com/fx/post/domain/Comment.kt
- post/src/main/kotlin/com/fx/post/domain/Like.kt
- post/src/main/kotlin/com/fx/post/domain/Post.kt
- post/src/main/kotlin/com/fx/post/domain/PostMedia.kt
feat: post 모듈 내 도메인, 엔티티, 리포지토리 생성
- Domain 내부 @ Post 생성
@ Comment 생성
@ Like 생성
@ PostMedia 생성
- Entity 내부 @ BaseEntity 생성
@ PostEntity 생성
@ CommentEntity 생성
@ LikeEntity 생성
@ PostMediaEntity 생성
- Repository 내부 @ PostRepository 생성
@ CommentRepository 생성
@ LikeRepository 생성
@ PostMediaRepository 생성
> feat: post 모듈 내 도메인, 엔티티, 리포지토리 생성

- gateway/src/main/resources/application.yml
> feat: gateway에 post 라우팅 추가

- post/src/main/resources/application.yml
refactor: post 모듈 application.yml 파일 환경변수로 변경
> refactor: post 모듈 application.yml 파일 환경변수로 변경

- user/src/main/kotlin/com/fx/user/adapter/in/web/dto/UserLoginRequest.kt
- user/src/main/kotlin/com/fx/user/adapter/security/CustomOAuth2UserService.kt
- user/src/main/kotlin/com/fx/user/adapter/security/CustomSuccessHandler.kt
- user/src/main/kotlin/com/fx/user/adapter/security/JwtProvider.kt
- user/src/main/kotlin/com/fx/user/application/in/dto/UserLoginCommand.kt
- user/src/main/kotlin/com/fx/user/application/in/dto/UserOAuthCommand.kt
- user/src/main/kotlin/com/fx/user/application/in/dto/UserSignUpCommand.kt
- user/src/main/kotlin/com/fx/user/application/service/UserCommandService.kt
- user/src/main/kotlin/com/fx/user/exception/JwtException.kt
- user/src/main/kotlin/com/fx/user/exception/errorcode/JwtErrorCode.kt
- user/src/main/kotlin/com/fx/user/exception/errorcode/UserErrorCode.kt
- user/src/main/kotlin/com/fx/user/exception/handler/JwtExceptionHandler.kt
> feat: Exception & 유효성 검증 처리

- post/src/main/java/com/fx/post/adapter/out/persistence/repository/LikeRepository.java
- post/src/main/java/com/fx/post/adapter/out/persistence/repository/PostRepository.java
- post/src/main/kotlin/com/fx/post/adapter/in/web/PostApiAdapter.kt
- post/src/main/kotlin/com/fx/post/adapter/out/persistence/PostPersistenceAdapter.kt
- post/src/main/kotlin/com/fx/post/application/in/PostCommandUseCase.kt
- post/src/main/kotlin/com/fx/post/application/out/persistence/PostPersistencePort.kt
- post/src/main/kotlin/com/fx/post/application/service/PostCommandService.kt
feat: 내가 좋아요한 게시글 목록 조회 개발
- 성능을 위해 2중 조인 JPQL 사용
- nickname, profileImageUrl, mediaUrls 미구현
> feat: 내가 좋아요한 게시글 목록 조회 개발

- gateway/build.gradle.kts
- gateway/src/main/kotlin/com/fx/gateway/filter/AuthenticationFilter.kt
- global/src/main/kotlin/com/fx/global/api/Api.kt
- global/src/main/kotlin/com/fx/global/exception/UnauthorizedException.kt
- global/src/main/kotlin/com/fx/global/exception/errorcode/UnauthorizedErrorCode.kt
- global/src/main/kotlin/com/fx/global/exception/handler/GlobalExceptionHandler.kt
- global/src/main/kotlin/com/fx/global/interceptor/AuthorizationInterceptor.kt
- global/src/main/kotlin/com/fx/global/resolver/AuthenticatedUserResolver.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/UserInternalApiAdapter.kt
- user/src/main/kotlin/com/fx/user/adapter/security/JwtAuthenticationFilter.kt
- user/src/main/kotlin/com/fx/user/application/in/UserCommandUseCase.kt
- user/src/main/kotlin/com/fx/user/application/service/UserCommandService.kt
- user/src/main/kotlin/com/fx/user/config/security/SecurityConfig.kt
1. Global 모듈 내 Resolver 및 Interceptor 에서 커스텀 예외처리
2. 매 검증 마다 User Module 로 검증 API를 요청하는 대신, Gateway 에서 직접 검증하도록 변경
> refactor: Global / Gateway 모듈 리팩토링

- user/build.gradle.kts
- user/src/main/kotlin/com/fx/user/config/swagger/SwaggerConfig.kt
- user/src/main/resources/application-swagger.yml
- user/src/main/resources/application.yml
> feat: User 모듈 내 swagger 추가

- global/src/main/kotlin/com/fx/global/annotation/hexagonal/WebInputAdapter.kt
- global/src/main/kotlin/com/fx/global/annotation/hexagonal/WebOutputAdapter.kt
- post/src/main/kotlin/com/fx/post/adapter/in/web/PostApiAdapter.kt
- post/src/main/kotlin/com/fx/post/adapter/out/web/impl/UserWebAdapter.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/ProfileApiAdapter.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/UserApiAdapter.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/UserOpenApiAdapter.kt
feat: WebAdapter(Input, Output) 어노테이션 개발
- WebAdapter -> WebInputAdapter 변경
- WebOutputAdapter 추가
> feat: WebAdapter(Input, Output) 어노테이션 개발

- gateway/src/main/resources/application-auth.yml
- gateway/src/main/resources/application.yml
- post/src/main/resources/application.yml
> feat: application-auth.yml 추가

- user/src/main/java/com/fx/user/adapter/out/persistence/entity/FollowEntity.java
- user/src/main/java/com/fx/user/adapter/out/persistence/repository/FollowRepository.java
- user/src/main/kotlin/com/fx/user/adapter/in/web/FollowApiAdapter.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/ProfileApiAdapter.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/UserOpenApiAdapter.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/dto/follow/FollowResponse.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/dto/profile/ProfileInfoResponse.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/dto/profile/ProfileUpdateRequest.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/dto/user/TokenResponse.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/dto/user/UserIdResponse.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/dto/user/UserLoginRequest.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/dto/user/UserSignUpRequest.kt
- user/src/main/kotlin/com/fx/user/adapter/out/persistence/FollowPersistenceAdapter.kt
- user/src/main/kotlin/com/fx/user/adapter/out/persistence/ProfilePersistenceAdapter.kt
- user/src/main/kotlin/com/fx/user/application/in/FollowCommandUseCase.kt
- user/src/main/kotlin/com/fx/user/application/out/FollowPersistencePort.kt
- user/src/main/kotlin/com/fx/user/application/out/ProfilePersistencePort.kt
- user/src/main/kotlin/com/fx/user/application/service/FollowCommandService.kt
- user/src/main/kotlin/com/fx/user/application/service/ProfileCommandService.kt
- user/src/main/kotlin/com/fx/user/application/service/ProfileQueryService.kt
- user/src/main/kotlin/com/fx/user/domain/Follow.kt
- user/src/main/kotlin/com/fx/user/exception/FollowException.kt
- user/src/main/kotlin/com/fx/user/exception/errorcode/FollowErrorCode.kt
- user/src/main/kotlin/com/fx/user/exception/handler/FollowExceptionHandler.kt
- user/src/main/kotlin/com/fx/user/exception/handler/JwtExceptionHandler.kt
자기 자신에게 팔로우하거나, 이미 팔로우가 요청된 경우 Exception
상대 프로필이 Private 인 경우 status -> PENDING
> faet: Follow 기능 개발

- user/src/main/kotlin/com/fx/user/adapter/in/web/FollowApiAdapter.kt
- user/src/main/kotlin/com/fx/user/adapter/out/persistence/FollowPersistenceAdapter.kt
- user/src/main/kotlin/com/fx/user/application/in/FollowCommandUseCase.kt
- user/src/main/kotlin/com/fx/user/application/out/FollowPersistencePort.kt
- user/src/main/kotlin/com/fx/user/application/service/FollowCommandService.kt
- user/src/main/kotlin/com/fx/user/exception/errorcode/FollowErrorCode.kt
> feat: unfollow 기능 개발

- user/src/main/java/com/fx/user/adapter/out/persistence/entity/FollowEntity.java
- user/src/main/kotlin/com/fx/user/adapter/in/web/FollowApiAdapter.kt
- user/src/main/kotlin/com/fx/user/application/in/FollowCommandUseCase.kt
- user/src/main/kotlin/com/fx/user/application/service/FollowCommandService.kt
- user/src/main/kotlin/com/fx/user/domain/Follow.kt
> feat: 팔로우 승인 API 개발

- media/src/main/kotlin/com/fx/media/adapter/in/web/MediaApiAdapter.kt
- media/src/main/kotlin/com/fx/media/adapter/out/persistence/MediaPersistenceAdapter.kt
- media/src/main/kotlin/com/fx/media/application/in/MediaCommandUseCase.kt
- media/src/main/kotlin/com/fx/media/application/out/persistence/MediaPersistencePort.kt
- media/src/main/kotlin/com/fx/media/application/service/MediaCommandService.kt
- media/src/main/kotlin/com/fx/media/domain/Media.kt
- media/src/main/kotlin/com/fx/media/exception/errorcode/MediaErrorCode.kt
feat: 미디어 삭제 기능 개발
- userId가 다르거나 role이 ADMIN이 아닐 경우 삭제 실패
> feat: 미디어 삭제 기능 개발

- post/src/main/kotlin/com/fx/post/adapter/in/web/CommentApiAdapter.kt
- post/src/main/kotlin/com/fx/post/adapter/in/web/LikeApiAdapter.kt
- post/src/main/kotlin/com/fx/post/adapter/in/web/PostApiAdapter.kt
- post/src/main/kotlin/com/fx/post/adapter/in/web/dto/comment/CommentCreateRequest.kt
- post/src/main/kotlin/com/fx/post/adapter/in/web/dto/comment/CommentCreateResponse.kt
- post/src/main/kotlin/com/fx/post/adapter/in/web/dto/comment/CommentResponse.kt
- post/src/main/kotlin/com/fx/post/adapter/in/web/dto/comment/MyCommentResponse.kt
- post/src/main/kotlin/com/fx/post/adapter/in/web/dto/like/LikeUsersResponse.kt
- post/src/main/kotlin/com/fx/post/adapter/in/web/dto/post/PostCreateRequest.kt
- post/src/main/kotlin/com/fx/post/adapter/in/web/dto/post/PostCreateResponse.kt
- post/src/main/kotlin/com/fx/post/adapter/in/web/dto/post/PostResponse.kt
- post/src/main/kotlin/com/fx/post/adapter/in/web/dto/post/PostUpdateRequest.kt
- post/src/main/kotlin/com/fx/post/adapter/in/web/dto/post/PostUpdateResponse.kt
feat: Post 모듈 ApiAdapter의 DTO 폴더 분리
- Post, Comment, Like 별 분리
> feat: Post 모듈 ApiAdapter의 DTO 폴더 분리

- chat/Dockerfile
- eureka/Dockerfile
- gateway/Dockerfile
- media/Dockerfile
- post/Dockerfile
- user/Dockerfile
Multi stage 방식을 도입함으로써 43% 용량 감소
> feat: Multi stage build 방식의 Dockerfile 개발

- user/src/main/kotlin/com/fx/user/application/service/FollowCommandService.kt
- user/src/main/kotlin/com/fx/user/domain/FollowQuery.kt
> refactor: 팔로우/팔로워 중복 코드 제거

- media/src/main/kotlin/com/fx/media/adapter/in/web/MediaApiAdapter.kt
- media/src/main/kotlin/com/fx/media/application/service/MediaCommandService.kt
> feat: 파일 저장 로직 코루틴 비동기 처리

- user/src/main/java/com/fx/user/adapter/out/persistence/repository/FollowQueryRepository.java
- user/src/main/kotlin/com/fx/user/adapter/in/web/FollowApiAdapter.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/dto/follow/FollowSearchParam.kt
- user/src/main/kotlin/com/fx/user/application/in/dto/FollowQueryCommand.kt
- user/src/main/kotlin/com/fx/user/domain/FollowQuery.kt
refactor: createdAt -> id 기반으로 페이징 조회
> refactor: createdAt -> id 기반으로 페이징 조회

- global/build.gradle.kts
- global/src/main/kotlin/com/fx/global/exception/handler/GlobalExceptionHandler.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/FollowApiAdapter.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/ProfileApiAdapter.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/UserInternalApiAdapter.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/UserOpenApiAdapter.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/dto/profile/ProfileUpdateRequest.kt
- user/src/main/kotlin/com/fx/user/application/in/FollowCommandUseCase.kt
- user/src/main/kotlin/com/fx/user/application/in/ProfileCommandUseCase.kt
- user/src/main/kotlin/com/fx/user/application/in/UserCommandUseCase.kt
- user/src/main/kotlin/com/fx/user/application/in/dto/FollowQueryCommand.kt
- user/src/main/kotlin/com/fx/user/application/in/dto/ProfileUpdateCommand.kt
- user/src/main/kotlin/com/fx/user/application/service/ProfileCommandService.kt
feat: Validation 설정 및 exception handler 개발
> feat: Validation 설정 및 exception handler 개발

- media/src/main/resources/application-swagger.yml
- post/src/main/resources/application-swagger.yml
- user/src/main/resources/application-swagger.yml
refactor: https 적용으로 환경변수 설정 변경
> refactor: https 적용으로 환경변수 설정 변경

- gateway/src/main/resources/application.yml
> refactor: CORS 전체 출처 허용

- media/src/main/kotlin/com/fx/media/adapter/in/web/MediaInternalApiAdapter.kt
- media/src/main/kotlin/com/fx/media/adapter/in/web/dto/MediaInfo.kt
- media/src/main/kotlin/com/fx/media/adapter/in/web/dto/MediaUrlResponse.kt
- media/src/main/kotlin/com/fx/media/application/in/dto/MediaUrlCommand.kt
- media/src/main/kotlin/com/fx/media/application/service/MediaQueryService.kt
- post/src/main/kotlin/com/fx/post/adapter/out/web/impl/dto/MediaInfo.kt
- post/src/main/kotlin/com/fx/post/adapter/out/web/impl/dto/MediaUrlCommand.kt
- post/src/main/kotlin/com/fx/post/adapter/out/web/impl/dto/MediaUrlResponse.kt
- user/src/main/kotlin/com/fx/user/adapter/out/web/impl/dto/MediaInfo.kt
- user/src/main/kotlin/com/fx/user/adapter/out/web/impl/dto/MediaUrlCommand.kt
- user/src/main/kotlin/com/fx/user/adapter/out/web/impl/dto/MediaUrlResponse.kt
> feat: Media 내부 API 구조 변경

- post/src/main/kotlin/com/fx/post/adapter/in/web/dto/post/PostResponse.kt
- post/src/main/kotlin/com/fx/post/application/out/persistence/dto/PostInfo.kt
- post/src/main/kotlin/com/fx/post/application/service/LikeQueryService.kt
- post/src/main/kotlin/com/fx/post/application/service/PostQueryService.kt
feat: 게시글 조회 API response 수정
- mediaUrls -> mediaInfos(mediaId, mediaUrl)
> feat: 게시글 조회 API response 수정

- media/src/main/kotlin/com/fx/media/adapter/in/web/MediaApiAdapter.kt
- media/src/main/kotlin/com/fx/media/application/in/MediaQueryUseCase.kt
- media/src/main/kotlin/com/fx/media/application/service/MediaQueryService.kt
remove: Media 모듈 Context, ReferenceId에 따른 조회 API 삭제
> remove: Media 모듈 Context, ReferenceId에 따른 조회 API 삭제

- user/src/main/kotlin/com/fx/user/adapter/in/web/dto/follow/FollowUserResponse.kt
- user/src/main/kotlin/com/fx/user/adapter/in/web/dto/profile/InternalProfileInfoResponse.kt
- user/src/main/kotlin/com/fx/user/application/out/persistence/dto/FollowUserInfo.kt
- user/src/main/kotlin/com/fx/user/application/service/FollowQueryService.kt
- user/src/main/kotlin/com/fx/user/application/service/ProfileQueryService.kt
> refactor: mediaInfo 응답 통일

- user/src/main/kotlin/com/fx/user/adapter/in/web/FollowApiAdapter.kt
- user/src/main/kotlin/com/fx/user/application/in/FollowQueryUseCase.kt
- user/src/main/kotlin/com/fx/user/application/service/FollowQueryService.kt
feat: Follow 요청 목록 조회
- PENDING 상태 조회
> feat: Follow 요청 목록 조회

- docker-compose.yml
refactor: fix internal port
- 도커 내부 포트 고정
> refactor: fix internal port

- media/build.gradle.kts
- media/src/main/resources/application.yml
- post/build.gradle.kts
- post/src/main/resources/application.yml
- user/build.gradle.kts
- user/src/main/kotlin/com/fx/user/config/security/SecurityConfig.kt
- user/src/main/resources/application.yml
> feat: Spring actuator 추가
